spring.application.name=java-job-tracker

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/job-tracker
spring.datasource.password=example
spring.datasource.username=admin

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

server.port=8081