-- Dev-only sample data for the `jobs` table (NOT a Flyway migration).
-- Paste into Adminer's SQL command box (connected to the job-tracker DB) and run.
--
-- Notes:
--   * `id` is GENERATED ALWAYS AS IDENTITY -> do NOT insert it; Postgres assigns it.
--   * `created_at` is omitted -> defaults to CURRENT_TIMESTAMP.
--   * A few `applied_date` values are NULL (status SAVED) to exercise the nullable column.

INSERT INTO jobs (company, position, status, applied_date) VALUES
('Google',              'Senior Backend Engineer',        'INTERVIEWING', '2026-03-12'),
('Stripe',              'Full Stack Engineer',            'APPLIED',      '2026-04-02'),
('Atlassian',           'Java Developer',                 'REJECTED',     '2026-02-18'),
('Netflix',             'Platform Engineer',              'SCREENING',    '2026-04-21'),
('Shopify',             'Software Engineer II',           'APPLIED',      '2026-04-28'),
('Canva',               'Backend Engineer (Spring Boot)', 'OFFER',        '2026-03-30'),
('Datadog',             'Site Reliability Engineer',      'REJECTED',     '2026-01-22'),
('Twilio',              'Senior Software Engineer',       'APPLIED',      '2026-05-01'),
('Square',              'Full Stack Developer',           'GHOSTED',      '2026-02-09'),
('Airbnb',              'Backend Engineer',               'INTERVIEWING', '2026-04-15'),
('Uber',                'Software Engineer (Java)',       'REJECTED',     '2026-02-26'),
('Pinterest',           'Backend Engineer',               'APPLIED',      '2026-05-06'),
('Reddit',              'Full Stack Engineer',            'SCREENING',    '2026-05-10'),
('Coinbase',            'Senior Backend Engineer',        'APPLIED',      '2026-04-09'),
('DoorDash',            'Software Engineer',              'WITHDRAWN',    '2026-03-03'),
('Robinhood',           'Java Backend Engineer',          'REJECTED',     '2026-01-30'),
('Snowflake',           'Platform Engineer',              'INTERVIEWING', '2026-04-19'),
('Databricks',          'Software Engineer (Scala/JVM)',  'APPLIED',      '2026-05-04'),
('Confluent',           'Backend Engineer (Kafka)',       'SCREENING',    '2026-04-25'),
('HashiCorp',           'Go/Java Engineer',               'REJECTED',     '2026-02-14'),
('GitLab',              'Backend Engineer (Ruby/Go)',     'GHOSTED',      '2026-03-08'),
('Elastic',             'Java Engineer (Search)',         'APPLIED',      '2026-05-12'),
('MongoDB',             'Senior Software Engineer',       'INTERVIEWING', '2026-04-11'),
('Redis',               'Backend Engineer',               'APPLIED',      '2026-05-14'),
('Cloudflare',          'Systems Engineer',               'REJECTED',     '2026-02-01'),
('Okta',                'Full Stack Engineer',            'SCREENING',    '2026-04-23'),
('Auth0',               'Backend Engineer (Identity)',    'APPLIED',      '2026-05-07'),
('PayPal',              'Java Developer',                 'REJECTED',     '2026-01-18'),
('Adyen',               'Backend Engineer',               'OFFER',        '2026-03-26'),
('Klarna',              'Software Engineer (Java)',       'WITHDRAWN',    '2026-02-22'),
('Wise',                'Backend Engineer',               'INTERVIEWING', '2026-04-17'),
('Revolut',             'Full Stack Engineer',            'APPLIED',      '2026-05-09'),
('Monzo',               'Backend Engineer (Java)',        'REJECTED',     '2026-02-05'),
('Plaid',               'Software Engineer',              'SCREENING',    '2026-04-29'),
('Brex',                'Backend Engineer',               'APPLIED',      '2026-05-13'),
('Ramp',                'Full Stack Engineer',            'GHOSTED',      '2026-03-15'),
('Notion',              'Software Engineer',              'APPLIED',      '2026-05-16'),
('Figma',               'Backend Engineer',               'INTERVIEWING', '2026-04-13'),
('Linear',              'Full Stack Engineer',            'REJECTED',     '2026-02-28'),
('Vercel',              'Software Engineer (Node)',       'APPLIED',      '2026-05-02'),
('Netlify',             'Backend Engineer',               'WITHDRAWN',    '2026-03-19'),
('Render',              'Platform Engineer',              'APPLIED',      '2026-05-15'),
('Fly.io',              'Systems Engineer',               'SCREENING',    '2026-04-27'),
('Supabase',            'Backend Engineer (Postgres)',    'INTERVIEWING', '2026-04-08'),
('PlanetScale',         'Database Engineer',              'REJECTED',     '2026-02-11'),
('Grafana Labs',        'Go Engineer',                    'APPLIED',      '2026-05-11'),
('Sentry',              'Backend Engineer',               'GHOSTED',      '2026-03-06'),
('Postman',             'Full Stack Engineer',            'APPLIED',      '2026-05-18'),
('JetBrains',           'Java/Kotlin Engineer',           'OFFER',        '2026-04-01'),
('Red Hat',             'Software Engineer (Spring)',     'INTERVIEWING', '2026-04-05'),
('VMware',              'Java Developer',                 'REJECTED',     '2026-01-25'),
('SAP',                 'Backend Engineer',               'APPLIED',      '2026-05-03'),
('Oracle',              'Java Cloud Engineer',            'WITHDRAWN',    '2026-02-16'),
('IBM',                 'Software Engineer',              'REJECTED',     '2026-01-14'),
('Salesforce',          'Backend Engineer (Apex/Java)',  'SCREENING',    '2026-04-30'),
('Workday',             'Full Stack Engineer',            'APPLIED',      '2026-05-17'),
('Smols Labs',          'Grails Developer',               'SAVED',        NULL),
('Hometown Startup',    'Junior Backend Engineer',        'SAVED',        NULL),
('Stealth Fintech',     'Software Engineer (Spring)',     'SAVED',        NULL),
('Acme Corp',           'Full Stack Engineer (Groovy)',   'ACCEPTED',     '2026-03-22');
